In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('House_Price.csv')
df

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0             60         65.0     8450            7            5       2003   
1             20         80.0     9600            6            8       1976   
2             60         68.0    11250            7            5       2001   
3             70         60.0     9550            7            5       1915   
4             60         84.0    14260            8            5       2000   
...          ...          ...      ...          ...          ...        ...   
1455          60         62.0     7917            6            5       1999   
1456          20         85.0    13175            6            6       1978   
1457          70         66.0     9042            7            9       1941   
1458          20         68.0     9717            5            6       1950   
1459          20         75.0     9937            5            6       1965   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  WoodDeckSF  \
0             2003       196.0         706           0  ...           0   
1             1976         0.0         978           0  ...         298   
2             2002       162.0         486           0  ...           0   
3             1970         0.0         216           0  ...           0   
4             2000       350.0         655           0  ...         192   
...            ...         ...         ...         ...  ...         ...   
1455          2000         0.0           0           0  ...           0   
1456          1988       119.0         790         163  ...         349   
1457          2006         0.0         275           0  ...           0   
1458          1996         0.0          49        1029  ...         366   
1459          1965         0.0         830         290  ...         736   

      OpenPorchSF  EnclosedPorch  X3SsnPorch  ScreenPorch  PoolArea  MiscVal  \
0              61              0           0            0         0        0   
1               0              0           0            0         0        0   
2              42              0           0            0         0        0   
3              35            272           0            0         0        0   
4              84              0           0            0         0        0   
...           ...            ...         ...          ...       ...      ...   
1455           40              0           0            0         0        0   
1456            0              0           0            0         0        0   
1457           60              0           0            0         0     2500   
1458            0            112           0            0         0        0   
1459           68              0           0            0         0        0   

      MoSold  YrSold  HousePrice  
0          2    2008           1  
1          5    2007           1  
2          9    2008           1  
3          2    2006           0  
4         12    2008           1  
...      ...     ...         ...  
1455       8    2007           0  
1456       2    2010           1  
1457       5    2010           1  
1458       4    2010           0  
1459       6    2008           0  

[1460 rows x 37 columns]

In [2]:
df.isnull().sum()

MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
X1stFlrSF        0
X2ndFlrSF        0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
X3SsnPorch       0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
HousePrice       0
dtype: int64

In [3]:
X = df.drop(["HousePrice"], axis = 1)
X

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0             60         65.0     8450            7            5       2003   
1             20         80.0     9600            6            8       1976   
2             60         68.0    11250            7            5       2001   
3             70         60.0     9550            7            5       1915   
4             60         84.0    14260            8            5       2000   
...          ...          ...      ...          ...          ...        ...   
1455          60         62.0     7917            6            5       1999   
1456          20         85.0    13175            6            6       1978   
1457          70         66.0     9042            7            9       1941   
1458          20         68.0     9717            5            6       1950   
1459          20         75.0     9937            5            6       1965   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  GarageArea  \
0             2003       196.0         706           0  ...         548   
1             1976         0.0         978           0  ...         460   
2             2002       162.0         486           0  ...         608   
3             1970         0.0         216           0  ...         642   
4             2000       350.0         655           0  ...         836   
...            ...         ...         ...         ...  ...         ...   
1455          2000         0.0           0           0  ...         460   
1456          1988       119.0         790         163  ...         500   
1457          2006         0.0         275           0  ...         252   
1458          1996         0.0          49        1029  ...         240   
1459          1965         0.0         830         290  ...         276   

      WoodDeckSF  OpenPorchSF  EnclosedPorch  X3SsnPorch  ScreenPorch  \
0              0           61              0           0            0   
1            298            0              0           0            0   
2              0           42              0           0            0   
3              0           35            272           0            0   
4            192           84              0           0            0   
...          ...          ...            ...         ...          ...   
1455           0           40              0           0            0   
1456         349            0              0           0            0   
1457           0           60              0           0            0   
1458         366            0            112           0            0   
1459         736           68              0           0            0   

      PoolArea  MiscVal  MoSold  YrSold  
0            0        0       2    2008  
1            0        0       5    2007  
2            0        0       9    2008  
3            0        0       2    2006  
4            0        0      12    2008  
...        ...      ...     ...     ...  
1455         0        0       8    2007  
1456         0        0       2    2010  
1457         0     2500       5    2010  
1458         0        0       4    2010  
1459         0        0       6    2008  

[1460 rows x 36 columns]

In [4]:
Y = df["HousePrice"]
Y

0       1
1       1
2       1
3       0
4       1
       ..
1455    0
1456    1
1457    1
1458    0
1459    0
Name: HousePrice, Length: 1460, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

X_Train,X_Test,Y_Train,Y_Test = train_test_split(X,Y,test_size=0.3,random_state=0)
# x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
X_Train

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
64            60    75.850000     9375            7            5       1997   
682          120    63.354762     2887            6            5       1996   
960           20    50.000000     7207            5            7       1958   
1384          50    60.000000     9060            6            5       1939   
1100          30    60.000000     8400            2            5       1920   
...          ...          ...      ...          ...          ...        ...   
763           60    82.000000     9430            8            5       1999   
835           20    60.000000     9600            4            7       1950   
1216          90    68.000000     8930            6            5       1978   
559          120    46.160000     3196            7            5       2003   
684           60    58.000000    16770            7            5       1998   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  GarageArea  \
64            1998       573.0         739           0  ...         645   
682           1997         0.0        1003           0  ...         431   
960           2008         0.0         696           0  ...           0   
1384          1950         0.0         204           0  ...         280   
1100          1950         0.0         290           0  ...         246   
...            ...         ...         ...         ...  ...         ...   
763           1999       673.0        1163           0  ...         856   
835           1995         0.0         442           0  ...         436   
1216          1978         0.0           0           0  ...         539   
559           2004        18.0           0           0  ...         420   
684           1998        30.0           0           0  ...         486   

      WoodDeckSF  OpenPorchSF  EnclosedPorch  X3SsnPorch  ScreenPorch  \
64           576           36              0           0            0   
682          307            0              0           0            0   
960          117            0              0           0            0   
1384           0            0              0           0            0   
1100           0            0              0           0            0   
...          ...          ...            ...         ...          ...   
763            0          128              0           0          180   
835          290            0              0           0            0   
1216           0            0              0           0            0   
559          143           20              0           0            0   
684            0           81              0           0            0   

      PoolArea  MiscVal  MoSold  YrSold  
64           0        0       2    2009  
682          0        0      11    2008  
960          0        0       2    2010  
1384         0        0      10    2009  
1100         0        0       1    2009  
...        ...      ...     ...     ...  
763          0        0       7    2009  
835          0        0       2    2010  
1216         0        0       4    2010  
559          0        0      10    2006  
684          0        0       6    2010  

[1022 rows x 36 columns]

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

rfc = RandomForestClassifier(n_estimators = 5, criterion = 'entropy', random_state = 0)
rfc.fit(X_Train,Y_Train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [7]:
? RandomForestClassifier

In [8]:
? RandomForestRegressor

In [9]:
Y_Pred = rfc.predict(X_Test)

In [10]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)
cm

array([[255,   9],
       [ 37, 137]])

In [11]:
from sklearn import metrics

print(metrics.accuracy_score(Y_Test, Y_Pred))
print(metrics.precision_score(Y_Test, Y_Pred))
print(metrics.recall_score(Y_Test, Y_Pred))
print(metrics.f1_score(Y_Test, Y_Pred))

0.8949771689497716
0.9383561643835616
0.7873563218390804
0.85625


In [12]:
rfc = RandomForestRegressor(n_estimators = 5, random_state = 0)
rfc.fit(X_Train,Y_Train)

RandomForestRegressor(n_estimators=5, random_state=0)

In [13]:
Y_Pred = rfc.predict(X_Test)
Y_Pred

array([0.6, 0.2, 0. , 1. , 0. , 0. , 0.8, 0. , 1. , 0. , 0.6, 0.2, 1. ,
       0. , 0. , 0. , 1. , 0. , 0. , 0.4, 0. , 0. , 0. , 0. , 0.4, 1. ,
       0.2, 0. , 1. , 0. , 0. , 0.2, 0. , 1. , 0.6, 0. , 1. , 0. , 1. ,
       1. , 0.8, 0. , 0.8, 1. , 1. , 0. , 0. , 0. , 0.4, 0. , 1. , 0. ,
       0. , 0. , 1. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0.4,
       0.6, 0. , 1. , 0. , 1. , 0. , 0. , 0. , 0.8, 0. , 1. , 0. , 0. ,
       1. , 0. , 0. , 0. , 0. , 0. , 0.8, 1. , 0. , 0.8, 0. , 0. , 0.8,
       0.8, 0.4, 1. , 0.4, 0. , 1. , 0.4, 0. , 0.4, 0.8, 0.4, 0. , 0. ,
       0. , 0.8, 0. , 0. , 0.2, 0. , 0. , 0. , 0.4, 0. , 0.2, 0.2, 0.6,
       0. , 0.6, 1. , 0.4, 0.2, 0. , 1. , 0.8, 0.8, 1. , 0.6, 1. , 0. ,
       0.8, 0.6, 0.2, 0. , 0. , 1. , 0. , 0.4, 0. , 0.4, 0. , 0. , 0.8,
       0. , 0. , 0.2, 1. , 0. , 1. , 1. , 0. , 1. , 1. , 0.6, 0. , 0.8,
       0. , 0.6, 0.2, 0. , 0. , 0. , 0.4, 0. , 1. , 0. , 0. , 1. , 1. ,
       0.2, 0. , 0. , 0.4, 0. , 0. , 0. , 0. , 0.8, 0. , 0. , 1.

In [14]:
print(metrics.mean_absolute_error(Y_Test, Y_Pred))
print(metrics.mean_squared_error(Y_Test, Y_Pred))

# 50-den assa jaksy!!!
print(metrics.r2_score(Y_Test, Y_Pred))

0.13287671232876713
0.08063926940639271
0.6632236154649946


In [15]:
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor

gbc = GradientBoostingClassifier(n_estimators=5, random_state=0)
gbc.fit(X_Train, Y_Train)

GradientBoostingClassifier(n_estimators=5, random_state=0)

In [16]:
Y_Pred = gbc.predict(X_Test)
Y_Pred

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,

In [17]:
cm = confusion_matrix(Y_Test, Y_Pred)
cm

array([[250,  14],
       [ 51, 123]])

In [18]:
print(metrics.accuracy_score(Y_Test, Y_Pred))
print(metrics.precision_score(Y_Test, Y_Pred))
print(metrics.recall_score(Y_Test, Y_Pred))
print(metrics.f1_score(Y_Test, Y_Pred))

0.8515981735159818
0.8978102189781022
0.7068965517241379
0.7909967845659164


In [19]:
gbc = GradientBoostingRegressor(n_estimators=5, random_state=0)
gbc.fit(X_Train, Y_Train)

GradientBoostingRegressor(n_estimators=5, random_state=0)

In [20]:
Y_Pred = gbc.predict(X_Test)
Y_Pred

array([0.4274498 , 0.29260572, 0.23126599, 0.56815801, 0.23126599,
       0.23126599, 0.60644543, 0.23126599, 0.60644543, 0.25340702,
       0.58939822, 0.44455023, 0.60644543, 0.23126599, 0.23126599,
       0.23126599, 0.55777826, 0.23126599, 0.23126599, 0.49980415,
       0.23126599, 0.23126599, 0.23126599, 0.23126599, 0.31687852,
       0.55023181, 0.44012144, 0.23126599, 0.60644543, 0.23126599,
       0.36563145, 0.40909055, 0.23126599, 0.60644543, 0.60644543,
       0.25340702, 0.60644543, 0.23126599, 0.60644543, 0.60644543,
       0.38238233, 0.23126599, 0.5111993 , 0.60644543, 0.60644543,
       0.36563145, 0.23126599, 0.23126599, 0.3715245 , 0.23126599,
       0.60644543, 0.23126599, 0.23126599, 0.23126599, 0.60644543,
       0.23126599, 0.23126599, 0.60644543, 0.23126599, 0.23126599,
       0.23126599, 0.23126599, 0.23126599, 0.23126599, 0.40942839,
       0.3402831 , 0.23126599, 0.60644543, 0.23126599, 0.55023181,
       0.36992414, 0.23126599, 0.23126599, 0.5771146 , 0.23126

In [21]:
print(metrics.mean_absolute_error(Y_Test, Y_Pred))
print(metrics.mean_squared_error(Y_Test, Y_Pred))

# 50-den assa jaksy!!!
print(metrics.r2_score(Y_Test, Y_Pred))

0.3516443774291465
0.14329941991939324
0.401534005681468


In [22]:
from xgboost import XGBClassifier, XGBRegressor

xgb = XGBRegressor()
xgb.fit(X_Train, Y_Train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [23]:
Y_Pred = xgb.predict(X_Test)
Y_Pred

array([ 5.94514906e-01,  3.44384573e-02, -1.87716610e-03,  9.08876061e-01,
       -1.36833442e-02, -1.32965213e-02,  9.94819641e-01,  1.93554536e-03,
        1.06453300e+00, -7.70483166e-03,  9.05660331e-01,  4.35491651e-01,
        9.85958934e-01, -1.42389489e-02, -2.20418274e-02, -3.31973145e-03,
        7.70582139e-01,  1.62262991e-02,  7.62482956e-02,  7.31162429e-01,
        4.06320021e-02, -3.94188159e-04, -8.80533829e-03,  3.90002914e-02,
        2.26739973e-01,  8.20267022e-01,  1.16065577e-01,  5.97307365e-03,
        9.99584734e-01, -2.24556029e-03, -3.82394344e-02,  3.43814582e-01,
        7.08662905e-03,  1.00464785e+00,  1.00313449e+00,  3.21902066e-01,
        9.82545495e-01,  2.87240976e-03,  1.00642157e+00,  1.03928375e+00,
        7.22566903e-01, -4.20527952e-03,  8.60123456e-01,  1.00417364e+00,
        1.01922786e+00, -1.24829717e-01, -4.95570339e-03, -2.61370861e-03,
        1.89817443e-01, -3.46103194e-03,  1.01310873e+00, -1.41172099e-03,
        1.04296058e-02, -

In [24]:
print(metrics.mean_absolute_error(Y_Test, Y_Pred))
print(metrics.mean_squared_error(Y_Test, Y_Pred))

# 50-den assa jaksy!!!
print(metrics.r2_score(Y_Test, Y_Pred))

0.13954220189256183
0.08201144068857441
0.6574929722340023


In [25]:
xgb = XGBClassifier()
xgb.fit(X_Train, Y_Train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [26]:
Y_Pred = xgb.predict(X_Test)
Y_Pred

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,

In [27]:
print(metrics.accuracy_score(Y_Test, Y_Pred))
print(metrics.precision_score(Y_Test, Y_Pred))
print(metrics.recall_score(Y_Test, Y_Pred))
print(metrics.f1_score(Y_Test, Y_Pred))

0.908675799086758
0.9135802469135802
0.8505747126436781
0.8809523809523809
