In [17]:
import numpy as np
import pandas as pd

In [18]:
dataset = pd.read_csv('House_Price.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [20]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[7.00000e+01 6.00000e+01 6.60000e+03 ... 0.00000e+00 1.20000e+01
  2.00900e+03]
 [8.00000e+01 7.59500e+01 1.07840e+04 ... 0.00000e+00 5.00000e+00
  2.00700e+03]
 [8.00000e+01 6.53135e+01 1.02460e+04 ... 0.00000e+00 5.00000e+00
  2.00600e+03]
 ...
 [9.00000e+01 6.80000e+01 8.93000e+03 ... 0.00000e+00 4.00000e+00
  2.01000e+03]
 [1.20000e+02 4.61600e+01 3.19600e+03 ... 0.00000e+00 1.00000e+01
  2.00600e+03]
 [6.00000e+01 5.80000e+01 1.67700e+04 ... 0.00000e+00 6.00000e+00
  2.01000e+03]]
[0 0 0 ... 0 1 1]
[[2.0000e+01 9.0250e+01 3.2668e+04 ... 0.0000e+00 3.0000e+00 2.0070e+03]
 [5.0000e+01 7.9000e+01 9.4900e+03 ... 0.0000e+00 8.0000e+00 2.0060e+03]
 [5.0000e+01 6.2876e+01 7.0150e+03 ... 0.0000e+00 7.0000e+00 2.0090e+03]
 ...
 [2.0000e+01 7.0000e+01 9.1000e+03 ... 0.0000e+00 9.0000e+00 2.0060e+03]
 [2.0000e+01 8.9000e+01 1.0991e+04 ... 0.0000e+00 1.2000e+01 2.0070e+03]
 [3.0000e+01 6.7000e+01 8.7770e+03 ... 0.0000e+00 5.0000e+00 2.0080e+03]]
[1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
print(X_train)
print(X_test)

[[ 0.31760564 -0.47891472 -0.39328519 ... -0.09424625  2.10547895
   0.87440704]
 [ 0.55467325  0.25209728  0.02284815 ... -0.09424625 -0.46803343
  -0.61931481]
 [ 0.55467325 -0.23538919 -0.03066039 ... -0.09424625 -0.46803343
  -1.36617573]
 ...
 [ 0.79174085 -0.11226293 -0.16154745 ... -0.09424625 -0.83567806
   1.62126796]
 [ 1.50294367 -1.11322232 -0.73184109 ... -0.09424625  1.37018969
  -1.36617573]
 [ 0.08053804 -0.57057767  0.61820526 ... -0.09424625 -0.10038881
   1.62126796]]
[[-0.86773239  0.90748736  2.1993926  ... -0.09424625 -1.20332268
  -0.61931481]
 [-0.15652957  0.39188328 -0.10585083 ... -0.09424625  0.63490044
  -1.36617573]
 [-0.15652957 -0.3471034  -0.35201001 ... -0.09424625  0.26725582
   0.87440704]
 ...
 [-0.86773239 -0.02059998 -0.14463955 ... -0.09424625  1.00254507
  -1.36617573]
 [-0.86773239  0.85019802  0.04343601 ... -0.09424625  2.10547895
  -0.61931481]
 [-0.63066478 -0.15809441 -0.17676457 ... -0.09424625 -0.46803343
   0.12754611]]


In [23]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [24]:
print(classifier.predict(X_train))

[0 0 0 ... 0 1 1]


In [25]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[199  21]
 [ 20 125]]


0.8876712328767123