In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('House_Price.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [5]:
print(X_train)
print('\n\n\n')
print(X_test)

[[6.00000000e+01 7.58500000e+01 9.37500000e+03 ... 0.00000000e+00
  2.00000000e+00 2.00900000e+03]
 [1.20000000e+02 6.33547619e+01 2.88700000e+03 ... 0.00000000e+00
  1.10000000e+01 2.00800000e+03]
 [2.00000000e+01 5.00000000e+01 7.20700000e+03 ... 0.00000000e+00
  2.00000000e+00 2.01000000e+03]
 ...
 [9.00000000e+01 6.80000000e+01 8.93000000e+03 ... 0.00000000e+00
  4.00000000e+00 2.01000000e+03]
 [1.20000000e+02 4.61600000e+01 3.19600000e+03 ... 0.00000000e+00
  1.00000000e+01 2.00600000e+03]
 [6.00000000e+01 5.80000000e+01 1.67700000e+04 ... 0.00000000e+00
  6.00000000e+00 2.01000000e+03]]




[[2.0000e+01 9.0250e+01 3.2668e+04 ... 0.0000e+00 3.0000e+00 2.0070e+03]
 [5.0000e+01 7.9000e+01 9.4900e+03 ... 0.0000e+00 8.0000e+00 2.0060e+03]
 [5.0000e+01 6.2876e+01 7.0150e+03 ... 0.0000e+00 7.0000e+00 2.0090e+03]
 ...
 [2.0000e+01 9.1000e+01 1.0437e+04 ... 0.0000e+00 8.0000e+00 2.0080e+03]
 [2.0000e+01 6.7000e+01 9.8080e+03 ... 0.0000e+00 3.0000e+00 2.0090e+03]
 [2.0000e+01 1.0000e+02 1.

In [6]:
print(y_train)
print('\n\n\n')
print(y_test)

[1 0 0 ... 0 1 1]




[1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1
 0 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1
 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0
 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0
 1 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0
 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 1 1 0 1 0
 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 0 0 1
 0 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1
 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 1
 1 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0 0 0 0 1 1
 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0
 1 1 1 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 1 1]


In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
print(X_train)
print('\n\n\n')
print(X_test)

[[ 0.08034002  0.2526718  -0.11597694 ... -0.09516792 -1.58780093
   0.86541406]
 [ 1.50416954 -0.32086972 -0.74672245 ... -0.09516792  1.73520088
   0.1196694 ]
 [-0.86887966 -0.93386408 -0.32674394 ... -0.09516792 -1.58780093
   1.61115872]
 ...
 [ 0.79225478 -0.10764954 -0.15923862 ... -0.09516792 -0.84935609
   1.61115872]
 [ 1.50416954 -1.11012318 -0.71668232 ... -0.09516792  1.36597846
  -1.37181992]
 [ 0.08034002 -0.56665762  0.60294461 ... -0.09516792 -0.11091124
   1.61115872]]




[[-0.86887966  0.91364342  2.14850443 ... -0.09516792 -1.21857851
  -0.62607526]
 [-0.1569649   0.39725934 -0.10479696 ... -0.09516792  0.62753361
  -1.37181992]
 [-0.1569649  -0.34284528 -0.34540965 ... -0.09516792  0.25831119
   0.86541406]
 ...
 [-0.86887966  0.94806903 -0.01273223 ... -0.09516792  0.62753361
   0.1196694 ]
 [-0.86887966 -0.15355035 -0.07388187 ... -0.09516792 -1.21857851
   0.86541406]
 [-0.86887966  1.3611763   0.22856099 ... -0.09516792 -1.21857851
   1.61115872]]


In [9]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state = 0)
logreg.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [10]:
? LogisticRegression

In [11]:
print(logreg.coef_)

[[-0.35370694  0.08433318  1.08079049  1.9630537   0.66966267  1.28889468
   0.85576999  0.06858776  0.8459342   0.25743069  0.26333739  1.26363261
   0.37211121  1.20211713  0.01238832  1.29332177  0.18596988 -0.20328551
   0.5519724   0.28049834 -0.43731105 -0.49411279  0.47325833 -0.01417138
  -0.50615286 -0.0293222   0.3023192   0.26467586  0.36088391  0.15850633
  -0.17238115  0.03723709  0.08692301 -0.0761111   0.1769223   0.26519409]]


In [12]:
print(logreg.intercept_)

[-1.91821812]


In [13]:
y_pred = logreg.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[250  14]
 [ 26 148]]


0.908675799086758