In [79]:
import metrics as metrics
import pandas as pd
import numpy as np

In [80]:
X=np.array([[-2,0,1],[1,-1,2],[1,0,1]])
Y=np.array([1,0,3])
X,Y

(array([[-2,  0,  1],
        [ 1, -1,  2],
        [ 1,  0,  1]]),
 array([1, 0, 3]))

In [81]:
X_tr = np.transpose(X)
X_tr

array([[-2,  1,  1],
       [ 0, -1,  0],
       [ 1,  2,  1]])

In [82]:
X_tr_X = np.dot(X_tr, X)
X_tr_X

array([[ 6, -1,  1],
       [-1,  1, -2],
       [ 1, -2,  6]])

In [83]:
X_tr_X_inv = np.linalg.inv(X_tr_X)
X_tr_X_inv

array([[0.22222222, 0.44444444, 0.11111111],
       [0.44444444, 3.88888889, 1.22222222],
       [0.11111111, 1.22222222, 0.55555556]])

In [84]:
coef = np.dot(X_tr_X_inv, X_tr)
coef

array([[-3.33333333e-01,  1.11022302e-16,  3.33333333e-01],
       [ 3.33333333e-01, -1.00000000e+00,  1.66666667e+00],
       [ 3.33333333e-01,  2.22044605e-16,  6.66666667e-01]])

In [85]:
params_analytic = np.dot(coef, Y)
params_analytic

array([0.66666667, 5.33333333, 2.33333333])

In [86]:
data = pd.read_csv("dataregression.csv")

In [87]:
data.head(10)

feature_1  feature_2  feature_3     label
0      0.146     -1.157      0.379  0.870982
1      1.286      0.658     -1.769 -3.705259
2     -1.872     -0.426     -0.022 -1.576071
3      0.949      0.958      0.694  3.962416
4     -1.985      0.727      1.181  2.981715
5      0.741     -0.393      0.083  0.862554
6     -1.194     -1.970     -1.347 -6.187324
7      1.474      0.899     -1.009 -0.975111
8      0.193     -0.171      0.072  0.505087
9     -0.643     -2.255      1.427  2.423583

In [88]:
X = data.iloc[:, 0:3].values
Y = data.iloc[:, 3].values

In [89]:
X, Y

(array([[ 0.146, -1.157,  0.379],
        [ 1.286,  0.658, -1.769],
        [-1.872, -0.426, -0.022],
        [ 0.949,  0.958,  0.694],
        [-1.985,  0.727,  1.181],
        [ 0.741, -0.393,  0.083],
        [-1.194, -1.97 , -1.347],
        [ 1.474,  0.899, -1.009],
        [ 0.193, -0.171,  0.072],
        [-0.643, -2.255,  1.427]]),
 array([ 0.87098153, -3.70525948, -1.57607053,  3.96241584,  2.9817153 ,
         0.86255406, -6.18732382, -0.97511125,  0.50508739,  2.42358325]))

In [90]:
X = np.hstack([ np.ones((10, 1)), X]) # y=ax+b*1

In [91]:
X

array([[ 1.   ,  0.146, -1.157,  0.379],
       [ 1.   ,  1.286,  0.658, -1.769],
       [ 1.   , -1.872, -0.426, -0.022],
       [ 1.   ,  0.949,  0.958,  0.694],
       [ 1.   , -1.985,  0.727,  1.181],
       [ 1.   ,  0.741, -0.393,  0.083],
       [ 1.   , -1.194, -1.97 , -1.347],
       [ 1.   ,  1.474,  0.899, -1.009],
       [ 1.   ,  0.193, -0.171,  0.072],
       [ 1.   , -0.643, -2.255,  1.427]])

In [92]:
X_tr = np.transpose(X)
X_tr_X = np.dot(X_tr, X)
X_tr_X_inv = np.linalg.inv(X_tr_X)
coef = np.dot(X_tr_X_inv, X_tr)
params_analytic = np.dot(coef, Y)

In [93]:
params_analytic

array([0.31749375, 0.78032738, 0.74979223, 3.08462768])

In [94]:
teta_grad_start = np.zeros(4)
learning_rate = 0.001 
epsilon = 0.00001
max_iter = 100000

def step(teta):
    return teta - learning_rate * (1.0/10) * np.dot(np.transpose(X), (np.dot(X, teta) - Y))

teta_GD = teta_grad_start
for i in range(max_iter):
    teta_GD_new = step(teta_GD)
    if np.sum(np.abs(teta_GD_new - teta_GD)) <= epsilon:
        break
    else:
        teta_GD = teta_GD_new
        
print(i)
print(teta_GD)

8454
[0.31673068 0.77492892 0.75208069 3.07801993]


In [95]:
from sklearn.linear_model import LinearRegression

In [96]:
LR = LinearRegression()

In [97]:
X = data.iloc[:, 0:3].values
Y = data.iloc[:, 3].values
LR.fit(X, Y)

LinearRegression()

In [98]:
LR.coef_, LR.intercept_

(array([0.78032738, 0.74979223, 3.08462768]), 0.3174937465999658)

In [99]:
A=np.array([[0.9,0.21,-0.456],[0.345,-0.456,0.1234],[0.344,-0.455,1.09]])

In [100]:
from sklearn.tree import DecisionTreeRegressor
DTR=DecisionTreeRegressor()
DTR.fit(X, Y)

DecisionTreeRegressor()

In [101]:
from sklearn.neighbors import KNeighborsRegressor
KNR=KNeighborsRegressor()
KNR.fit(X,Y)

KNeighborsRegressor()

In [102]:
y_pred=DTR.predict(A)
y_pred

array([-1.57607053,  0.86255406,  3.96241584])

In [103]:
import sklearn from metrics
print("mse= " + str(metrics.mean_squared_error(y_test, y_pred)))
print("mae = " + str(metrics.mean_absolute_error(y_test, y_pred)))
print("r2 = " + str(metrics.r2_score(y_test, y_pred)))

SyntaxError: invalid syntax (600855954.py, line 1)

In [ ]:
y_pred=LR.predict(A)

In [ ]:
y_pred

In [ ]:
y_test=np.array([0.00001,0.456657,2.9045])

In [ ]:
from sklearn import metrics
print("mse= " + str(metrics.mean_squared_error(y_test, y_pred)))
print("mae = " + str(metrics.mean_absolute_error(y_test, y_pred)))
print("r2 = " + str(metrics.r2_score(y_test, y_pred)))